### ISSUE TITLE
A way to review comments before clicking them

### ISSUE THREAD

**Issue by GrumpyCrouton** [SOBotics/AdvancedFlagging#10]
I think there should be a way to view what a comment would be if posted.

For example, when hovering over a link like "Not an answer", it should display a tooltip which contains the comment that would be posted if that option was clicked.

Another thing I thought of was to have a sort of "confirmation" screen, so you click a link and it pops up a box basically asking if you are sure and displays the comment that will be posted - however I think the tooltip is a better idea because it doesn't require an extra click or anything, and it doesn't get in the way.

**Comment by rjrudman** [comment]
The links will now display a tooltip if they'll leave a comment. Thanks for the suggestion!
