### ISSUE TITLE
Metasmoke doesn't open in Safari

### ISSUE THREAD

**Issue by FelixSFD** [SOBotics/AdvancedFlagging#11]
Everytime I'm loading a page, the script tries to open metasmoke in a new tab, which doesn't work. Would it be possible to add an option in the footer that shows an Auth-URL when clicking it?

**Comment by rjrudman** [comment]
@FelixSFD Unfortunately, I haven't got a mac to test this myself on. If you click 'OK', visit another tab, and then come back to the SO page, does it display another prompt asking for the authentication token?

If it does, then we can easily add a link in the footer (until then, the link is: https://metasmoke.erwaysoftware.com/oauth/request?key=0a946b9419b5842f99b052d19c956302aa6c6dd5a420b043b20072ad2efc29e0 )

If it doesn't prompt for the code after losing focus to the tab, this may be a bit more difficult to implement, but it will be part of #7 when the configuration is properly fixed

**Comment by rjrudman** [comment]
I'd like to properly fix this for Safari on mac, but in the meantime, there are two new links in the footer:

![Footer image](https://i.imgur.com/YAfdLNa.png)

Here's the process to get smokey hooked up manually
1. When the initial prompt displays on the page, click Cancel. 
2. Click 'Get MetaSmoke key'. Save the key somewhere
3. Click 'Manually register MetaSmoke key'
4. Enter the saved key

**Comment by FelixSFD** [comment]
Yes, the script recognizes that I visited an other tab and displays the prompt for the code.

The workaround is good. Thanks :-)
