### ISSUE TITLE
Unchecking Downvote post for the Spam Flag Type causes all settings to be defaulted

### ISSUE THREAD

**Issue by HenryEcker** [SOBotics/AdvancedFlagging#220]
If I uncheck "Downvote" under spam settings:
<img width="965" alt="Screen Shot 2022-05-16 at 17 56 33" src="https://user-images.githubusercontent.com/22064330/168688977-7a5280a8-6e67-4d30-bdec-0dc4865f9602.png">

Click save and refresh the page. All AdvancedFlagging configurations get reset to the default. 

This appears to be due to [the following line](https://github.com/SOBotics/AdvancedFlagging/blob/470279371a677c7d4da49f1d58796dcb8743b62a/src/Configuration.ts#L80):
> ```typescript
> if (!globals.cachedFlagTypes.length || !globals.cachedFlagTypes[0]?.Downvote) cacheFlags();
> ```

I'm not sure what the intention of `!globals.cachedFlagTypes[0]?.Downvote` is, however, since Downvote is present in the first FlagType (spam) it pulls the value, which in this case is `false` since the "Downvote post" checkbox is unchecked. 

`globals.cachedFlagTypes[0]`:
```json
{
    "Id": 1,
    "DisplayName": "Spam",
    "FlagText": "",
    "Comments": {
        "Low": "",
        "High": ""
    },
    "ReportType": "PostSpam",
    "Feedbacks": {
        "Smokey": "tpu-",
        "Natty": "tp",
        "Guttenberg": "",
        "Generic Bot": "track"
    },
    "BelongsTo": "Red flags",
    "IsDefault": true,
    "SendWhenFlagRaised": true,
    "Downvote": false,
    "Enabled": true
}
```

With the above configuration `!globals.cachedFlagTypes[0]?.Downvote` => `!false` => `true` which in turn runs `cacheFlags()` which entirely blanks out all configurations.

If we're testing for a specific structure an explicit comparison to `undefined` might be better `globals.cachedFlagTypes[0]?.Downvote === undefined` or even `globals.cachedFlagTypes[0].hasOwnProperty('Downvote')`.

**Comment by double-beep** [comment]
This has been fixed (in `src`, not `dist`). My intention was to check if the `Downvote` property existed (it did not, in earlier versions of AF).
