### ISSUE TITLE
Dist file /dist/AdvancedFlagging.user.js is not updated

### ISSUE THREAD

**Issue by dippas** [SOBotics/AdvancedFlagging#229]
I just realized, after doing a unnecessary PR, that  `/dist/AdvancedFlagging.user.js` is not updated/compiled

**Comment by double-beep** [comment]
The dist file is updated when a new version is released.

**Comment by dippas** [comment]
yes I'm aware of that but for some reason it is not the same version as the source. I found it because of a missing class on dist file (when using user-script) - misalignment in the links - so I've clone the project and when running the dist file was automatically changed (that class was one of the changes)
