### ISSUE TITLE
Double configuration lines

### ISSUE THREAD

**Issue by slear** [SOBotics/AdvancedFlagging#252]
This happens with the latest version (1.3.10) using Microsoft Edge DEV

![image](https://user-images.githubusercontent.com/8234846/212337654-3261fa91-df94-4c7a-bbe1-f94ce87fea2c.png)

**Comment by slear** [comment]
Yes, this happened after install 1.3.10 and it is present on every SO page. It asked me to configure two times but it has not saved anything. I tried to unistall the script. As a result two lines disappeared but the other two are still there. Funny enough the script were still working (I mean I had the Advanced Flagging link even after the deinstall). Now I have reinstalled and I have again 4 lines and no configuration can be saved.

**Comment by double-beep** [comment]
@slear closing this now, if you face this issue with v2.0.0, ping me.
