### ISSUE TITLE
Get user name on FlagTypes.ts

### ISSUE THREAD

**Issue by sri-shree** [SOBotics/AdvancedFlagging#26]
Is there any way to get username( who post a answer ). I want to change some message and try to dig more on script. Actually Its not a bug but I don't know where I post this.
For example:

Welcome to StackOveflow [Want to get User name here]. However, this does not provide an answer to the question. You can search for similar questions, or refer to the related and linked questions on the right-hand side of the page to find an answer. If you have a related but different question, ask a new question, and include a link to this one to help provide context. See: Ask questions, get answers, no distractions

**Comment by rjrudman** [comment]
Done. The function now accepts a 'userDetails' which exposes 'Reputation' and 'AuthorName'.

So, for example, you could write:

```
{
    Id: 3242,
    DisplayName: 'Something',
    ReportType: 'AnswerNotAnAnswer',
    GetComment: (userDetails) => 'Hi ' + userDetails.AuthorName + '!'
}
```

**Comment by sri-shree** [comment]
Great work. Thanks.
