### ISSUE TITLE
Guttenberg: Different flag-text for wrong attribution

### ISSUE THREAD

**Issue by FelixSFD** [SOBotics/AdvancedFlagging#27]
Example: http://copypastor.sobotics.org/posts/217

In cases like that, we usually flag with a text like this: 
>[...]. The author only added a link to the other answer, which is not the [proper way of attribution](https://stackoverflow.blog/2009/06/25/attribution-required/).

**Comment by rjrudman** [comment]
Shouldn't be too difficult to add. Could you include the full flag text you'd like to see here?

**Comment by FelixSFD** [comment]
> This post is copied from [another answer](link), as can be seen [here](CopyPastor-link). The author only added a link to the other answer, which is [not the proper way of attribution](https://stackoverflow.blog/2009/06/25/attribution-required/).

Is markdown allowed in flag texts?

**Comment by Bhargav-Rao** [comment]
Link markdown is allowed.

**Comment by rjrudman** [comment]
@FelixSFD Done. After updating AF, you'll need to enable the option in configuration (bottom right of page, in the footer).
