### ISSUE TITLE
NAAhighrep is not upvoted

### ISSUE THREAD

**Issue by geisterfurz007** [SOBotics/AdvancedFlagging#29]
When the comment NAAlowrep already exists on a post and you select "Not an answer" from the list that comment gets upvoted.
This is not the case if the comment NAAhighrep already exists and "Not an answer" is selected from the dropdown menu.

**Comment by rjrudman** [comment]
Did the script add the comment again?

**Comment by geisterfurz007** [comment]
The comment was not added again.
If deleted posts work, this should be one: https://stackoverflow.com/questions/49887754/arm-template-for-bots/51078324#51078324
Essentially any of these: https://chat.stackoverflow.com/search?q=NAAHighrep&room=111347

**Comment by rjrudman** [comment]
Fixed! Turns out this was due to the way we were stripping markdown. Should work now, v1.0.1
