### ISSUE TITLE
AdvancedFlagging: Changing the configuration for a flag type wipes out the Smokey feedback option

### ISSUE THREAD

**Issue by PurpleMagick** [SOBotics/AdvancedFlagging#291]
Steps to reproduce:
1. Go to the bottom of a page and click the "AdvancedFlagging: edit comments and flags"
  ![image](https://github.com/SOBotics/AdvancedFlagging/assets/2600582/e8528f81-46f8-4c72-9819-2ff11dc7e09c)

2. Click "Edit" to change the configuration for a flag. For example Spam.
  ![image](https://github.com/SOBotics/AdvancedFlagging/assets/2600582/536758da-5e93-4235-8afa-8f7e1b8b6aff)
  ![image](https://github.com/SOBotics/AdvancedFlagging/assets/2600582/c7f97e43-ccb3-409b-90a2-5fedfc8dcdd4)

3. Save (does not matter if anything option is changed or not). At this point the problem has manifested. Go through the rest of the steps to see it
4. Reload the page.
5. Repeat 1. and 2. 

Expected: The choice for "Feedback to Smokey" should remain to whatever was before saving.
Actual: The choice is wiped and set to "(none)".

![image](https://github.com/SOBotics/AdvancedFlagging/assets/2600582/55073d5c-6cd2-4761-a04d-42dbc148ca95)

---

[This has been fixed as of 2023-01-23](https://github.com/SOBotics/AdvancedFlagging/commit/15ae5a1bfc299eaadea79ece3a8a781aeaedec64), however, that fix is not released yet. The latest release for AdvancedFlagging is from 2023-01-14.

The short summary of the technical issue is that for [for Smokey the possible flag values are 'tpu-', 'tp-', 'fp-', 'naa-](https://github.com/SOBotics/AdvancedFlagging/blob/3e785f5ab5d6566d041287c111c9b06d51a0feff/src/shared.ts#L47). However, when the ID for the radio button is generated via ```id: `advanced-flagging-${idedName}-feedback-${feedback}-${flagId}` ``` that results in an ID with a double dash near the end.

```
<input class="s-radio" type="radio" id="advanced-flagging-Smokey-feedback-tpu--1" name="advanced-flagging-1-feedback-to-Smokey" data-feedback="">
<label class="s-label flex--item" for="advanced-flagging-Smokey-feedback-tpu--1">tpu-</label>
```

When `data-feedback` is to be populated, the value for it (in the latest release) comes from `const [feedback] = radio.id.split('-').slice(-2, -1);` which produces an empty string. Then saving takes that empty value for the Smokey configuration.

**Comment by double-beep** [comment]
Thanks! I've published a new version, which should solve this issue. If the problem isn't gone, please ping me.
