### ISSUE TITLE
Feature request: auto-switch from deleting to flagging when picking spam or R/A

### ISSUE THREAD

**Issue by LunarWatcher** [SOBotics/AdvancedFlagging#298]
I'm a mod, so my delvotes are binding. This means that I've disabled the flag option by default, because I don't use it outside spam. However, this means I have to spend a whole extra two clicks on every single spam or R/A post to flag it rather than delete it.

Could we get an option that auto-disables delete and auto-enables flagging for R/A and spam posts? I imagine this is a very mod-specific use-case, so having a default-disabled option is probably better

**Comment by double-beep** [comment]
In 2.0.1:

- If a flag deletes a post (e.g. if it's the fourth red flag), then a delete vote will not be cast
- NAA/VLQ flagging is disabled for moderators.

Ping me if you find any bugs.
