### ISSUE TITLE
Red flag icon is not appear after flagged answer which indicate that answer is already flagged.

### ISSUE THREAD

**Issue by sri-shree** [SOBotics/AdvancedFlagging#32]
When ever I flagged from AF red flag appear which indicate that i already feed back (Flagged) that answer but now red flag is not appear ? I feel that this problem  is appear when SO change comment flagged style and now dark red icon indicate comment flag which is already flagged .Class or some thing change so AF is not able catch that and unable to indicate that. (I am not sure but I guess ). Already flagged answer also show in 10 k tools with red flag but now it's also missing on 10 k tools.

**Comment by rjrudman** [comment]
Fixed in 1.0.10. Thanks for your report!
