### ISSUE TITLE
Notice to indicate  that user  reached  daily flag limit

### ISSUE THREAD

**Issue by sri-shree** [SOBotics/AdvancedFlagging#36]
I don't remember exactly but I think previous version of AF indicate that user  reached  daily flag limit but In new version  it's gives wrong notification. Although  user  reached  daily flag limit it's notify user as "Flagged"  but actually there is not any flag raised. So it's better to give feedback to user like 'You reached  daily flag limit, Flag is not raise ------'

**Comment by rjrudman** [comment]
@sri-shree Unfortunately, I can't test and see what error is returned by the server. When you've used all the flags, can you try to flag a post and show me the response from SE? Be sure to remove any credentials/fkeys first
