### ISSUE TITLE
z-index issue with menu dropdown

### ISSUE THREAD

**Issue by danbopes** [SOBotics/AdvancedFlagging#39]
Seems there might have been an update to SO, that caused the editor buttons to pop above the AdvancedFlagging tooltip:

![](https://i.imgur.com/LqTbVAL.png)

A z-index of **3** on AdvancedFlaggings `dl` seems to correct the error.

**Comment by geisterfurz007** [comment]
If it were only for the cosmetics I wouldn't care too much but you can neither click Library nor Comment anymore because of this 😕

**Comment by rjrudman** [comment]
Thanks for the report. I've pushed [https://github.com/SOBotics/AdvancedFlagging/commit/8ecb535eba21849f2b3e095765bcced99c38273b](an updated) using the z-index of 3 as suggested. Version 1.0.16

**Comment by LunarWatcher** [comment]
Not entirely out of the woods yet: the config dialog conflicts too:

![image](https://user-images.githubusercontent.com/29489988/47914848-60353200-dea1-11e8-85e3-22902ba08979.png)
