### ISSUE TITLE
Add upvote to comment if already flagged

### ISSUE THREAD

**Issue by danbopes** [SOBotics/AdvancedFlagging#4]
If I use Advanced Flagging to mark a Link Only answer that already has a Link Only comment, instead of doing nothing, it should upvote the current auto-comment with an upvote. (This should work the same for the others).

**Comment by rjrudman** [comment]
Good idea. Will take a look into it, might be a bit tricky, as the text matches will need some manipulation. 
We can get the plain text comments, but we'll need to manipulate the comment text we're leaving to strip links, so we can do a proper text match

**Comment by rjrudman** [comment]
Implemented now. If we find a comment which is identical to ours (links and ' - From Review' are stripped), we'll automatically upvote the comment

**Comment by danbopes** [comment]
Did this functionality get removed?

**Comment by rjrudman** [comment]
Nope, it should still work.
Could you add a link to the post where it didn't work?

**Comment by rjrudman** [comment]
Oh, this has changed because we leave a different message for users < 50 reputation. The current code only up-votes identical comments (with links stripped out).

Here's the comment the script would have left: https://github.com/SOBotics/AdvancedFlagging/blob/master/src/FlagTypes.ts#L96

**Comment by rjrudman** [comment]
Fixed in 1.0.12 - this accidentally broke, as automatic refactoring removed `index` as no longer needed here:  https://github.com/SOBotics/AdvancedFlagging/commit/3ff435b96272909bf8408b03b4906153cfccb24f :(
