### ISSUE TITLE
Not working with Microsoft Edge

### ISSUE THREAD

**Issue by double-beep** [SOBotics/AdvancedFlagging#40]
Hello, I am using Microsoft Edge with TamperMonkey installed as a userscript manager.

However, as tested, it is not working on Microsoft Edge, but working on Chrome. Why this?

**Comment by FelixSFD** [comment]
AFAIK, AdvancedFlagging can only be used in a browser ;-)

**Comment by double-beep** [comment]
What do you mean?

**Comment by rjrudman** [comment]
The userscript is only supported on chrome, and I believe works fine on firefox. Haven't looked at edge. If you'd like to make a pull request fixing it for edge, please feel free. But otherwise, marking this as won't do, sorry
