### ISSUE TITLE
Alert Box hasn't been encoded correctly

### ISSUE THREAD

**Issue by dippas** [SOBotics/AdvancedFlagging#43]
Hi, I noticed while voting to close  an old question (typo reason), that the alert box has some HTML not properly encoded

![image](https://user-images.githubusercontent.com/10220287/59507865-d79d5c00-8e9b-11e9-9a05-849fab4b8041.png)

**Comment by jdd-software** [comment]
Are you sure this right repo?, I would guess this issue is related to https://github.com/SO-Close-Vote-Reviewers/UserScripts/blob/master/SECloseVoteRequestGenerator.user.js not to AdvancedFlagging.

**Comment by jdd-software** [comment]
AdvancedFlagging does not send cv-pls, issue on wrong repo
