### ISSUE TITLE
"Failed to send feedback to Natty" in Safari

### ISSUE THREAD

**Issue by paulroub** [SOBotics/AdvancedFlagging#54]
When flagging a comment, the flag and comment are added, GenericBot succeeds, but it _always_ ends with "Failed to send feedback to Natty"

The error appears to happen in this block (unminified from the minified version):

```js
this.GetChannelPage(t).then(t => {
    const r = $("#active-user", $(t)).attr("class").match(/user-(\d+)/);
    r && r.length && e(parseInt(r[1], 10)),
    n("Could not find user id")
})
```

Based on the console output:

> Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating '$("#active-user",$(t)).attr("class").match')

The same version of the script works for me in Chrome, Firefox, etc. I haven't heard of others failing in Safari (macOS 11.1, Safari 14 -- although it happened in 13.x as well), but perhaps I've missed something?

Running Tampermonkey 4.11.6117

**Comment by double-beep** [comment]
Are you logged in to chat?

**Comment by double-beep** [comment]
The element is probably not found, but there's no reason why this might happen, as I guess you are logged in to chat...
