### ISSUE TITLE
Better comment detection

### ISSUE THREAD

**Issue by rjrudman** [SOBotics/AdvancedFlagging#6]
As an extension of #4 - we should be smarter about comments we auto-upvote. This may extend to have an entirely configurable flag system.

**Comment by danbopes** [comment]
A bit of a note. I clicked advanced flagging => thanks on [this answer](https://stackoverflow.com/questions/45858300/dplyr-rename-error-contains-unknown-variables/48444615#48444615) (Soon to be deleted). It should have upvoted Rob's comment, but didn't.

**Comment by rjrudman** [comment]
@danbopes Those comments should now be working
